### ISSUE TITLE
Regular SSL read timeouts

### ISSUE THREAD

**Issue by juicetin** [dyvosvit/telegb#1]
Hi,

It seems that every few minutes, I get this error, requiring a restart that pushes through all recent buys/sells again:

`
  File "telepl.py", line 159, in <module>                                                                                                                                                                      
    pollResult=pollCoinsTrades24h()                                                                                                                                                                            
  File "telepl.py", line 124, in pollCoinsTrades24h                                                                                                                                                            
    tradeHistory24h = testapi.returnTradeHistory('All')                                                                                                                                                        
  File "telepl.py", line 116, in returnTradeHistory                                                                                                                                                            
    return self.api_query('returnTradeHistory',{"currencyPair":currencyPair})                                                                                                                                  
  File "telepl.py", line 88, in api_query                                                                                                                                                                      
    ret = urlopen(Request('https://poloniex.com/tradingApi', post_data, headers))                                                                                                                              
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen                                                                                                                                                   
    return opener.open(url, data, timeout)                                                                                                                                                                     
  File "/usr/lib/python2.7/urllib2.py", line 429, in open                                                                                                                                                      
    response = self._open(req, data)                                                                                                                                                                           
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open                                                                                                                                                     
    '_open', req)                                                                                                                                                                                              
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain                                                                                                                                               
    result = func(*args)                                                                                                                                                                                       
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open                                                                                                                                               
    context=self._context)                                                                                                                                                                                     
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open                                                                                                                                                  
    r = h.getresponse(buffering=True)                                                                                                                                                                          
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse                                                                                                                                              
    response.begin()                                                                                                                                                                                           
  File "/usr/lib/python2.7/httplib.py", line 438, in begin                                                                                                                                                     
    version, status, reason = self._read_status()                                                                                                                                                              
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status                                                                                                                                              
    line = self.fp.readline(_MAXLINE + 1)                                                                                                                                                                      
  File "/usr/lib/python2.7/socket.py", line 480, in readline                                                                                                                                                   
    data = self._sock.recv(self._rbufsize)                                                                                                                                                                     
  File "/usr/lib/python2.7/ssl.py", line 766, in recv                                                                                                                                                          
    return self.read(buflen)                                                                                                                                                                                   
  File "/usr/lib/python2.7/ssl.py", line 653, in read                                                                                                                                                          
    v = self._sslobj.read(len)                                                                                                                                                                                 
ssl.SSLError: ('The read operation timed out',)  
`

I'll also take a look into why this might be happening if I have some spare time over the weekend.

**Comment by utdrmac** [comment]
Same issue. The script should not die when this happens.

```
[root@ip-172-31-35-58 telegb]# python telepl.py
Internet is lagging, we've got SSL error
Internet is lagging, we've got SSL error
Internet is lagging, we've got SSL error
Traceback (most recent call last):
  File "telepl.py", line 212, in <module>
    worker()
  File "telepl.py", line 170, in worker
    pollResult=pollCoinsTrades24h()
  File "telepl.py", line 136, in pollCoinsTrades24h
    tradeHistory24h = testapi.returnTradeHistory('All')
  File "telepl.py", line 130, in returnTradeHistory
    return self.api_query('returnTradeHistory',{"currencyPair":currencyPair})
  File "telepl.py", line 110, in api_query
    jsonRet = json.loads(ret.read())
  File "/usr/lib64/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib64/python2.7/httplib.py", line 578, in read
    return self._read_chunked(amt)
  File "/usr/lib64/python2.7/httplib.py", line 638, in _read_chunked
    value.append(self._safe_read(amt))
  File "/usr/lib64/python2.7/httplib.py", line 693, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib64/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib64/python2.7/ssl.py", line 759, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len or 1024)
ssl.SSLError: ('The read operation timed out',)
```

**Comment by utdrmac** [comment]
@juicetin The recent merge should help with this. It does a better job of error catching

**Comment by juicetin** [comment]
Thanks for the heads up @utdrmac! I no longer have anything set up (primarily around the botting) to test it out, but I'll go ahead and close the issue as it's been merged in already :)
